# Copyright (c) 2016-2025 Crave.io Inc. All rights reserved
IMGTAG?=accupara/postgres
IMGVER_BASE?=rockylinux_8
#Rocky linux 8 is not available for ppc64le or s390x
IMGVER_TARGETS?=aarch64 x86_64

include $(shell git rev-parse --show-toplevel)/Makefile.build
