# Copyright (c) 2016-2026 Crave.io Inc. All rights reserved
IMGTAG?=accupara/jobserver
IMGVER_BASE?=golang-1.24.9-bookworm
IMGVER_TARGETS?=aarch64 x86_64 ppc64le

include $(shell git rev-parse --show-toplevel)/Makefile.build
