# Copyright (c) 2016-2022 Crave.io Inc. All rights reserved
IMGTAG?=accupara/ti
IMGVER?=ccs

include $(shell git rev-parse --show-toplevel)/Makefile.build

download:
	wget https://software-dl.ti.com/ccs/esd/CCSv10/CCS_10_1_0/exports/CCS10.1.0.00010_linux-x64.tar.gz
