# Copyright (c) 2016-2025 Crave.io Inc. All rights reserved
IMGTAG?=accupara/centos
IMGVER_BASE?=7
# I'm dropping ppc64le because I dont want to deal with binfmt
IMGVER_TARGETS?=aarch64 x86_64

include $(shell git rev-parse --show-toplevel)/Makefile.build
