# Copyright (c) 2016-2025 Crave.io Inc. All rights reserved
IMGTAG?=accupara/centos
IMGVER?=7
# Too much time wasted trying to figure out why non-x86 dont work. Giving up.
#IMGVER_TARGETS?=aarch64 x86_64 ppc64le

include $(shell git rev-parse --show-toplevel)/Makefile.build
