# Copyright (c) 2016-2021 Crave.io Inc. All rights reserved
FROM accupara/centos:6
MAINTAINER Crave.io Inc. "contact@crave.io"

RUN sudo yum update -y \
 && sudo yum install -y \
        glibc-static \
        zlib-static
