# Copyright (c) 2016-2019 Crave.io Inc. All rights reserved
IMGTAG?=accupara/yocto
IMGVER?=ubuntu_1404

CONTEXT_DIR=$(shell readlink -f ../..)
DOCKERFILE=$(shell readlink -f ./Dockerfile)

include $(shell git rev-parse --show-toplevel)/Makefile.build
