# Copyright (c) 2016-2017 Accupara Inc. All rights reserved
IMGTAG?=accupara/yocto
IMGVER?=ubuntu_1404

CONTEXT_DIR=../..
DOCKERFILE=$(shell $(readlink -f Dockerfile))

include $(shell git rev-parse --show-toplevel)/Makefile.build
