# Copyright (c) 2016-2022 Crave.io Inc. All rights reserved
FROM accupara/ubuntu:20.04

RUN set -x \
 && sudo apt-get update -y \
 && sudo apt-get install -y \
    python3-pip \
 && sudo python3 -m pip install \
    tensorflow
