# Copyright (c) 2016-2021 Crave.io Inc. All rights reserved
FROM accupara/ubuntu:18.04
MAINTAINER Crave.io Inc. "contact@crave.io"

RUN set -x \
 && sudo apt-get update -y \
 && sudo apt-get install -y \
    python-pip \
 && sudo pip install \
    tensorflow_gpu
