# Copyright (c) 2016-2023 Crave.io Inc. All rights reserved
IMGTAG?=accupara/pyinstaller
IMGVER_BASE?=centos_7
IMGVER_TARGETS?=aarch64 x86_64 ppc64le

include $(shell git rev-parse --show-toplevel)/Makefile.build
