# Copyright (c) 2016-2024 Crave.io Inc. All rights reserved
IMGTAG?=accupara/nvidia-cuda
IMGVER_BASE?=12.x_20.04
IMGVER_TARGETS?=aarch64 x86_64

include $(shell git rev-parse --show-toplevel)/Makefile.build
