# Copyright (c) 2016 Accupara Inc. All rights reserved
IMGTAG?=accupara/yocto
IMGVER?=latest
#IMGVER?=$(shell /bin/date "+%Y%m%d.%H%M%S")

include $(shell git rev-parse --show-toplevel)/Makefile.build
