# Copyright (c) 2016-2024 Crave.io Inc. All rights reserved
FROM accupara/fedora:39

RUN sudo dnf update -y && \
    sudo dnf groupinstall -y "Development Tools" && \
    sudo dnf install -y \
     bc \
     clang-devel \
     createrepo \
     docbook-dtds \
     docbook-style-xsl \
     dos2unix \
     e2fsprogs-devel \
     hdf5 \
     hdf5-devel \
     krb5-devel \
     libcurl-devel \
     libicu-devel \
     libselinux-devel \
     libuuid-devel \
     libxml2-devel \
     libxslt-devel \
     llvm-devel \
     lz4-devel \
     m4 \
     openldap-devel \
     openssl-devel \
     pam-devel \
     perl \
     perl-generators \
     perl-ExtUtils-Embed \
     perl-IPC-Run \
     python3-devel \
     readline-devel \
     rpmdevtools \
     selinux-policy \
     systemd-devel \
     systemtap-sdt-devel \
     tcl-devel
