[program:cron]
priority=10
directory=/home/admin
command=/usr/sbin/cron
user=admin
environment=HOME="/home/admin",USER="admin"
autostart=false
autorestart=false
stopsignal=QUIT
stdout_logfile=/var/log/cron.log
stderr_logfile=/var/log/cron.err
