#!/bin/bash
# Copyright (c) 2016-2024 Crave.io Inc. All rights reserved

if [ "$1" == "sync" ]; then
    echo "syncing repo in the devspace is forbidden, please use crave clone"
    exit 1
fi

if [[ "$@" == *"envsetup.sh"* ]]; then
    echo -e "Executing 'envsetup.sh' directly is forbidden in devspace. \n Read the information here for proper sending your command in buildnode  \n https://opendroid.pugzarecute.com/wiki/Crave_Devspace"
    exit 1
fi


exec /usr/bin/repo.real $@
