# Copyright (c) 2016-2018 Crave.io Inc. All rights reserved

# DO NOT COMPILE bb10 automatically. It requires a UI to build..
# SUBDIRS=bb10 android
SUBDIRS=maemo harmattan aosp

include $(shell git rev-parse --show-toplevel)/Makefile.subdirs
