# Copyright (c) 2016-2017 Accupara Inc. All rights reserved

# DO NOT COMPILE bb10 automatically. It requires a UI to build..
# SUBDIRS=bb10
SUBDIRS=maemo harmattan android aosp

include $(shell git rev-parse --show-toplevel)/Makefile.subdirs
