# Copyright (c) 2016-2017 Accupara Inc. All rights reserved
SUBDIRS=armv4t armv5te armv6 armv7a armv7a-hf m28evk m53evk mips powerpc powerpc-4xx powerpc-4xx-softfloat powerpc-e500v2 powerpc-softfloat
include $(shell git rev-parse --show-toplevel)/Makefile.subdirs
