#!/bin/bash
# Copyright (c) 2019 crave.io Inc. All rights reserved

set -e -o pipefail

if [[ -f /run/secrets/DEBUG ]]; then
	export DEBUG=$(cat $i)
fi

if [[ "$DEBUG" = "1" ]]; then
	set -x
fi

# Load env vars
for i in $(env|grep '/run/secrets')
do
	varName=$(echo $i|awk -F '[=]' '{print $1}'|sed 's/_FILE//')
	varFile=$(echo $i|awk -F '[=]' '{print $2}')
	eval "export $varName=$(cat $varFile)"
done

# If crave config variable is declared, lets write the crave config and use it
if [[ "${CRAVE_CONFIG}" != "" ]]; then
	# Lets create crave config at the root so it is accessed by crave from any workdir
	echo "$CRAVE_CONFIG" | sudo tee /crave.conf 1>/dev/null 2>&1
    sudo chown admin:admin /crave.conf
    sudo chmod 444 /crave.conf
fi

# Lets set crave as cmd if first argument is not a command
inputCmd="$(echo $1|awk '{print $1}')"
inputCmd="$(which $inputCmd 2>/dev/null || true)"
if [[ ! -f $inputCmd ]]; then
	cmd="/crave"
    if [[ "$DEBUG" = "1" ]]; then
	    cmd+=" -v"
    fi
	cmd+=" $@"
else
	params=$(echo "$@"|awk '{$1=""; print $0}')
	cmd="${inputCmd}${params}"
fi

# Run crave with all given params to this entrypoint script
if [[ "$DEBUG" = "1" ]]; then
	echo "CMD: eval $cmd"
fi
eval "$cmd"
