# Copyright (c) 2016-2019 Crave.io Inc. All rights reserved
FROM centos:6
MAINTAINER Crave.io Inc. "contact@crave.io"

COPY bin/crave /crave-bin
COPY crave /usr/local/bin

ENTRYPOINT [ "/crave" ]
CMD [ "crave" ]
