# Copyright (c) 2016-2025 Crave.io Inc. All rights reserved
SUBDIRS=dbchecker devspace docker-builder drpacker libdeploy ollama-with-ui pipeline wp
include $(shell git rev-parse --show-toplevel)/Makefile.subdirs
