# Copyright (c) 2016-2018 Accupara Inc. All rights reserved
FROM codestar/circleci-scala-sbt-git:latest
MAINTAINER Accupara Inc. "contact@accupara.com"

# Just add the libc6 compat
RUN apk add --update libc6-compat
