# Copyright (c) 2016-2023 Crave.io Inc. All rights reserved
IMGTAG?=accupara/postgres
IMGVER_BASE?=centos_7
IMGVER_TARGETS?=aarch64 x86_64

include $(shell git rev-parse --show-toplevel)/Makefile.build
