# Copyright (c) 2016-2026 Crave.io Inc. All rights reserved
IMGTAG?=us-west1-docker.pkg.dev/crave-228104/docker/qtbuild
IMGVER?=2019

WINDOWS=yes

include $(shell git rev-parse --show-toplevel)/Makefile.build
