# Copyright (c) 2016-2024 Crave.io Inc. All rights reserved
IMGTAG?=accupara/postgres
IMGVER_BASE?=rocklylinux_9
# Rockylinux 9 is avaialable for s390x, but not building it rt now
IMGVER_TARGETS?=aarch64 x86_64 ppc64le

include $(shell git rev-parse --show-toplevel)/Makefile.build
