# Copyright (c) 2016-2022 Crave.io Inc. All rights reserved
SUBDIRS=ubuntu centos debian fedora xpra scratchbox golang mxe java rustlang nvidia
include $(shell git rev-parse --show-toplevel)/Makefile.subdirs
