# Copyright (c) 2016-2021 Crave.io Inc. All rights reserved
SUBDIRS=ubuntu centos debian fedora xpra scratchbox golang mxe java rustlang
include $(shell git rev-parse --show-toplevel)/Makefile.subdirs
