# Copyright (c) 2016-2022 Crave.io Inc. All rights reserved
SUBDIRS=k8s envoy linkerd onap-so vitess grafana-loki prometheus vsphere-csi-driver wasmedge
include $(shell git rev-parse --show-toplevel)/Makefile.subdirs
