# Copyright (c) 2016-2020 Crave.io Inc. All rights reserved
SUBDIRS=k8s envoy linkerd onap-so vitess grafana-loki prometheus vsphere-csi-driver
include $(shell git rev-parse --show-toplevel)/Makefile.subdirs
