# Copyright (c) 2016-2017 Accupara Inc. All rights reserved
FROM accupara/ubuntu:16.04
MAINTAINER Accupara Inc. "contact@accupara.com"

RUN sudo apt-get update && \
    sudo apt-get install -y \
        autoconf \
        automake \
        clang \
        perl
