# Copyright (c) 2016-2022 Crave.io Inc. All rights reserved
FROM accupara/qt5:linux

RUN set -x \
 && sudo apt-get update \
 && sudo apt-get install -y \
        libqt5svg5-dev \
        qtscript5-dev
