# Copyright (c) 2016-2025 Crave.io Inc. All rights reserved
IMGTAG?=us-west1-docker.pkg.dev/crave-228104/docker/tak-civ-android
IMGVER?=latest

include $(shell git rev-parse --show-toplevel)/Makefile.build
