# Copyright (c) 2016-2020 Crave.io Inc. All rights reserved
FROM accupara/yocto:ubuntu_1604
MAINTAINER Crave.io Inc. "contact@crave.io"

RUN sudo apt-get update \
 && sudo apt-get install -y \
        repo
