# Copyright (c) 2016-2018 Accupara Inc. All rights reserved
FROM accupara/yocto:ubuntu_1604
MAINTAINER Accupara Inc. "contact@accupara.com"

RUN sudo apt-get update \
 && sudo apt-get install -y \
        repo
