# Copyright (c) 2016-2020 Crave.io Inc. All rights reserved
IMGTAG?=accupara/yocto
IMGVER?=ubuntu_1710

CONTEXT_DIR=$(shell readlink -f ../..)
DOCKERFILE=$(shell readlink -f ./Dockerfile)

include $(shell git rev-parse --show-toplevel)/Makefile.build
