# Copyright (c) 2016-2023 Crave.io Inc. All rights reserved
FROM accupara/centos:6

RUN set -x \
 && sudo yum update -y \
 && sudo yum install -y \
    flex \
    glibc-devel.i686 \
    gmp \
    libgcc.i686 \
    libunistring \
    perl \
    readline-devel \
    svn \
    texinfo-tex \
    zip
