# Copyright (c) 2016-2024 Crave.io Inc. All rights reserved
IMGTAG?=accupara/clickhouse
IMGVER_BASE?=ubuntu
IMGVER_TARGETS?=aarch64 x86_64 ppc64le

include $(shell git rev-parse --show-toplevel)/Makefile.build
