# Copyright (c) 2016-2026 Crave.io Inc. All rights reserved
IMGTAG?=accupara/clickhouse
IMGVER_BASE?=ubuntu
IMGVER_TARGETS?=aarch64 x86_64

include $(shell git rev-parse --show-toplevel)/Makefile.build
