# Copyright (c) 2016-2017 Accupara Inc. All rights reserved
FROM accupara/fedora:26
MAINTAINER Accupara Inc. "contact@accupara.com"

RUN sudo dnf update -y \
 && sudo dnf install -y \
        bison \
        flex \
        gettext \
        krb5-devel \
        libxml2-devel \
        libxslt-devel \
        openssl-devel \
        pam-devel \
        pam_krb5 \
        perl-devel \
        perl-ExtUtils-Embed \
        python2-devel \
        python3-devel \
        readline-devel \
        tcl-devel \
        uuid-devel \
        zlib-devel
