# Copyright (c) 2016-2017 Accupara Inc. All rights reserved
IMGTAG?=accupara/android_qt
IMGVER?=5.8
#IMGVER?=$(shell /bin/date "+%Y%m%d.%H%M%S")

include $(shell git rev-parse --show-toplevel)/Makefile.build
