# Copyright (c) 2016-2026 Crave.io Inc. All rights reserved
SUBDIRS=android emsdk java pyinstaller qt rustlang scratchbox ubuntu-dind xpra
include $(shell git rev-parse --show-toplevel)/Makefile.subdirs
