# Copyright (c) 2016-2025 Crave.io Inc. All rights reserved
SUBDIRS=xpra java rustlang android pyinstaller ubuntu-dind scratchbox qt emsdk
include $(shell git rev-parse --show-toplevel)/Makefile.subdirs
