# Copyright (c) 2016-2024 Crave.io Inc. All rights reserved
SUBDIRS=ferretdb foundationdb mariadb mongodb mysql orioledb postgres rocksdb timescaledb clickhouse pg_cpu_test
include $(shell git rev-parse --show-toplevel)/Makefile.subdirs
