# Copyright (c) 2016-2023 Crave.io Inc. All rights reserved
SUBDIRS=postgres foundationdb timescaledb mariadb mysql rocksdb orioledb mongodb ferretdb
include $(shell git rev-parse --show-toplevel)/Makefile.subdirs
