# Copyright (c) 2016-2026 Crave.io Inc. All rights reserved
SUBDIRS=ferretdb foundationdb mariadb mongodb mysql postgres rocksdb timescaledb clickhouse pg_cpu_test redis
include $(shell git rev-parse --show-toplevel)/Makefile.subdirs
