# Copyright (c) 2016-2022 Crave.io Inc. All rights reserved
FROM accupara/centos:6

RUN set -x \
 && sudo yum -y update \
 && sudo yum install -y \
    bzip2-devel \
    db4-devel \
    gdbm-devel \
    libffi-devel \
    libzip-devel \
    ncurses-devel \
    openssl-devel \
    readline-devel \
    sqlite-devel \
    tk-devel \
    uuid-devel \
    xz-devel
