# Copyright (c) 2016-2024 Crave.io Inc. All rights reserved

# Pretty sure this will ensure that the container cannot be pushed to the Docker hub
IMGTAG?=accupara/abuse-sdl
IMGVER?=latest

include $(shell git rev-parse --show-toplevel)/Makefile.build
