# Copyright (c) 2016-2026 Crave.io Inc. All rights reserved
IMGTAG?=accupara/qt6
IMGVER?=ubuntu_2404
# For the moment we only allow Qt6 for x86
#IMGVER_TARGETS?=aarch64 x86_64

include $(shell git rev-parse --show-toplevel)/Makefile.build
