# Copyright (c) 2016-2025 Crave.io Inc. All rights reserved
IMGTAG?=accupara/qt6
IMGVER_BASE?=ubuntu_2404
IMGVER_TARGETS?=aarch64 x86_64

include $(shell git rev-parse --show-toplevel)/Makefile.build
