# Copyright (c) 2016-2026 Crave.io Inc. All rights reserved
IMGTAG?=accupara/debian
IMGVER_BASE?=11
# Only these two here https://hub.docker.com/_/debian/tags under 11
IMGVER_TARGETS?=aarch64 x86_64

include $(shell git rev-parse --show-toplevel)/Makefile.build
