# Copyright (c) 2016-2025 Crave.io Inc. All rights reserved
IMGTAG?=accupara/drpacker
IMGVER_BASE?=golang-1.25-bookworm
IMGVER_TARGETS?=aarch64 x86_64 ppc64le

include $(shell git rev-parse --show-toplevel)/Makefile.build
