# Copyright (c) 2016-2025 Crave.io Inc. All rights reserved
IMGTAG?=accupara/drpacker
IMGVER_BASE?=golang-1.23-bullseye
IMGVER_TARGETS?=aarch64 x86_64

include $(shell git rev-parse --show-toplevel)/Makefile.build
