# Copyright (c) 2016-2018 Accupara Inc. All rights reserved
FROM accupara/ubuntu:16.04
MAINTAINER Accupara Inc. "contact@accupara.com"

# Follow the steps laid out at http://www.mono-project.com/docs/compiling-mono/linux/

RUN sudo apt-get update && \
    sudo apt-get install -y \
         autoconf \
         automake \
         build-essential \
         cmake \
         gettext \
         git \
         libtool \
         libtool-bin \
         mono-devel
