# Copyright (c) 2016-2022 Crave.io Inc. All rights reserved
FROM accupara/ubuntu:20.04

# Follow the steps laid out at http://www.mono-project.com/docs/compiling-mono/linux/

RUN set -x \
 && sudo apt-get update \
 && sudo apt-get install -y \
         autoconf \
         automake \
         build-essential \
         cmake \
         gettext \
         git \
         libtool \
         libtool-bin \
         mono-devel
