# Copyright (c) 2016-2025 Crave.io Inc. All rights reserved
SUBDIRS=ubuntu centos debian fedora rocky-linux golang nvidia arch opensuse
include $(shell git rev-parse --show-toplevel)/Makefile.subdirs
